title: Glossarist
# Used in page title, unless page.title is specified
description: Open-source terminology management solution
# Used in page title

font_awesome_kit_url: "https://kit.fontawesome.com/6c9fdda763.js"

email: open@ribose.org
baseurl: ""
# url: "https://glossarist.org"
twitter_username: riboseUS
github_username:  riboseinc

users:
  - entity: ISO/TC 211
    link:
      href: "https://geolexica.org/"
      title: Geolexica.org
    use_case_summary: >-
      ISO Technical Committee 211 “Geographic information/Geomatics”
      uses Glossarist for its MLGT database resource website.
  #- entity: OSGeo
  #  link:
  #    href: "https://osgeo.geolexica.org/"
  #    title: OSGeo.Geolexica.org
  - entity: IHO
    link:
      href: "https://iho.glossarist.org/"
      title: IHO vocabulary

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/