name: build

on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      - '!master'   # excludes master
      - '!staging'   # excludes master

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/checkout@master
      - name: Install NPM dependencies
        run: |
          yarn install
      - name: Build site
        run: |
          yarn build -d
